"""Audit event model and URL sanitisation for the M17 Network Audit panel.

This module defines :class:`NetworkAuditEvent` — the immutable record
persisted by :mod:`metis_app.network_audit.store` for every outbound
call METIS makes — and :func:`sanitize_url`, the helper that reduces a
full URL to the *only* two URL-shaped fields the audit panel is
allowed to remember: the hostname and the first path segment.

**Privacy invariants** (load-bearing; see ADR 0011):

- The ``query_params_stored`` field is ``Literal[False]`` at the
  type level and enforced at runtime in ``__post_init__``. Constructing
  an event with ``query_params_stored=True`` raises ``ValueError``.
  There is no code path in which query strings are persisted.
- :func:`sanitize_url` never returns anything beyond the hostname and
  the first path segment. Userinfo, port, query string, fragment, and
  the path beyond the first segment are dropped before the tuple is
  built. See the docstring's doctests for the full corpus of shapes.
- The URL sanitiser is unit-tested aggressively by
  ``tests/test_network_audit_events.py``. Do not loosen these
  invariants without first updating the ADR.

See ``plans/network-audit/plan.md`` (Phase 2) and
``docs/adr/0011-network-audit-retention.md`` for the full rationale.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Literal
from urllib.parse import urlsplit


@dataclass(frozen=True, slots=True)
class NetworkAuditEvent:
    """One outbound-call record for the audit panel.

    All fields are persisted to the SQLite store as-is. ``url_host``
    and ``url_path_prefix`` MUST be produced by :func:`sanitize_url` —
    feeding a raw URL into either field bypasses the privacy invariant
    and is a bug.

    Attributes:
        id: 26-character ULID (Crockford base32), generated by
            :func:`metis_app.network_audit.store.new_ulid`. Primary key
            in the SQLite store.
        timestamp: UTC, tz-aware. Callers MUST pass a timezone-aware
            ``datetime``; the store normalises to epoch milliseconds
            for indexing.
        method: HTTP method verb, e.g. ``"GET"``, ``"POST"``.
        url_host: Hostname only, lowercased, no port, no userinfo.
            See :func:`sanitize_url`.
        url_path_prefix: First path segment only, prefixed with ``/``.
            Empty path collapses to ``"/"``. See :func:`sanitize_url`.
        query_params_stored: Hard-coded ``False``. The type annotation
            makes this a static-check invariant; ``__post_init__``
            enforces it at runtime.
        provider_key: Either a key from
            :data:`metis_app.network_audit.providers.KNOWN_PROVIDERS`
            or the literal string ``"unclassified"``.
        trigger_feature: Free-form feature tag declared by the caller,
            e.g. ``"news_comet_worker"``, ``"autonomous_research"``,
            ``"gguf_install"``.
        size_bytes_in: Response payload size; ``None`` if not
            measured or the call failed before the body was read.
        size_bytes_out: Request payload size; ``None`` for plain GETs.
        latency_ms: Wall-clock latency of the call in milliseconds;
            ``None`` if the call was blocked before dispatch.
        status_code: HTTP status code; ``None`` if blocked or if the
            connection failed before a status line was read.
        user_initiated: ``True`` iff a human action in the current
            session directly caused this call. Background workers,
            autonomous research, skill-evolution runs, etc. all
            MUST pass ``False``. No inference from call-site — the
            caller declares this explicitly.
        blocked: ``True`` iff the kill-switch layer intercepted this
            call. Blocked calls are still recorded — the panel's
            promise is "show everything, including what we stopped".
    """

    id: str
    timestamp: datetime
    method: str
    url_host: str
    url_path_prefix: str
    query_params_stored: Literal[False]
    provider_key: str
    trigger_feature: str
    size_bytes_in: int | None
    size_bytes_out: int | None
    latency_ms: int | None
    status_code: int | None
    user_initiated: bool
    blocked: bool

    def __post_init__(self) -> None:
        # The type annotation is ``Literal[False]`` which mypy catches
        # statically. This runtime check catches ``True`` passed as
        # any truthy value and guards against a subclass or a dataclass
        # field-default bypass.
        if self.query_params_stored is not False:
            raise ValueError(
                "NetworkAuditEvent.query_params_stored MUST be False. "
                "Query strings are never persisted by the audit layer; "
                "see ADR 0011.",
            )
        if self.timestamp.tzinfo is None:
            raise ValueError(
                "NetworkAuditEvent.timestamp MUST be timezone-aware (UTC).",
            )


def sanitize_url(url: str) -> tuple[str, str]:
    """Return ``(host, path_prefix)`` for an outbound URL.

    Strips userinfo, port, query string, fragment, and any path
    content beyond the first segment. The returned tuple is the only
    URL-shaped data persisted by the audit layer.

    Behaviour:

    - Host is lowercased and port-stripped via ``urlsplit().hostname``.
    - Path prefix is the first non-empty segment, prepended with ``/``.
    - Empty / root paths collapse to ``"/"``.
    - Malformed URLs (no host parseable) return ``("unknown", "/")``.

    Doctests:

    >>> sanitize_url("https://api.openai.com/v1/chat/completions?api_key=SECRET&prompt=foo")
    ('api.openai.com', '/v1')
    >>> sanitize_url("https://hacker-news.firebaseio.com/v0/topstories.json")
    ('hacker-news.firebaseio.com', '/v0')
    >>> sanitize_url("http://localhost:1234/v1/chat/completions")
    ('localhost', '/v1')
    >>> sanitize_url("https://www.reddit.com/r/LocalLLaMA/hot.json")
    ('www.reddit.com', '/r')
    >>> sanitize_url("https://huggingface.co")
    ('huggingface.co', '/')
    >>> sanitize_url("https://fonts.googleapis.com/css2?family=Inter")
    ('fonts.googleapis.com', '/css2')
    """
    if not isinstance(url, str) or not url.strip():
        return ("unknown", "/")

    try:
        parts = urlsplit(url)
    except ValueError:
        return ("unknown", "/")

    # ``hostname`` lowercases, strips port and userinfo. For IPv6 it
    # returns the address without brackets, which is what we want.
    host = parts.hostname
    if not host:
        return ("unknown", "/")

    path = parts.path or ""
    # Split on "/" and take the first non-empty segment. An empty
    # path or a bare "/" collapses to "/".
    segments = [segment for segment in path.split("/") if segment]
    if not segments:
        return (host, "/")
    return (host, "/" + segments[0])


__all__ = [
    "NetworkAuditEvent",
    "sanitize_url",
]
