"""Tests for installer-generated launcher scripts.

These tests validate that the launcher generation logic in install_metis.sh
and install_metis.ps1 produces the expected routing behavior:
- `metis` => web UI (default)
- `metis --desktop` / `metis --gui` => Qt GUI (main.py)
- `metis --web` => web UI (backward-compatible no-op)
- `metis --cli ...` => CLI (forwarded args)
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).parent.parent
INSTALL_SH = REPO_ROOT / "scripts" / "install_metis.sh"
INSTALL_PS1 = REPO_ROOT / "scripts" / "install_metis.ps1"
README = REPO_ROOT / "README.md"


def extract_sh_launcher_template() -> str:
    """Extract the embedded bash launcher script from install_metis.sh."""
    content = INSTALL_SH.read_text(encoding="utf-8")
    match = re.search(
        r'cat > "\$LAUNCHER" <<LAUNCHER_EOF\s*\n(.+?)\nLAUNCHER_EOF',
        content,
        re.DOTALL,
    )
    assert match, "Could not find bash launcher template in install_metis.sh"
    return match.group(1)


def extract_ps1_launcher_template() -> str:
    """Extract the embedded PowerShell launcher script from install_metis.ps1."""
    content = INSTALL_PS1.read_text(encoding="utf-8")
    match = re.search(
        r'@"\s*\n(.+?)\n"@ \| Set-Content',
        content,
        re.DOTALL,
    )
    assert match, "Could not find PowerShell launcher template in install_metis.ps1"
    return match.group(1)


def extract_cmd_launcher_template() -> str:
    """Extract the embedded CMD launcher script from install_metis.ps1."""
    content = INSTALL_PS1.read_text(encoding="utf-8")
    start_marker = "CMD wrapper"
    start_idx = content.find(start_marker)
    if start_idx == -1:
        pytest.fail("Could not find CMD launcher template in install_metis.ps1")
    start_heredoc = content.find('@"', start_idx)
    end_heredoc = content.find('"@ | Set-Content -Path $LauncherCmd')
    if start_heredoc == -1 or end_heredoc == -1:
        pytest.fail("Could not find CMD launcher heredoc boundaries")
    template = content[start_heredoc + 3 : end_heredoc]
    return template.strip()


class TestBashLauncher:
    """Tests for the bash launcher generated by install_metis.sh."""

    def test_default_is_web_api_and_browser(self) -> None:
        """Default path should start the API, static web server, and open browser."""
        template = extract_sh_launcher_template()
        assert "uvicorn metis_app.api.app:app" in template, (
            "Default should start the API server"
        )
        assert "http.server" in template, "Default should start a static web server"
        assert "127.0.0.1:8000" in template, "Default API URL should be fixed"
        assert "127.0.0.1:3000" in template, "Default web URL should be fixed"

    def test_desktop_mode_routes_to_main_py(self) -> None:
        """--desktop flag should route to main.py."""
        template = extract_sh_launcher_template()
        assert "--desktop" in template, "Should check for --desktop flag"
        assert "main.py" in template, "Should run main.py for desktop mode"

    def test_gui_mode_routes_to_main_py(self) -> None:
        """--gui flag should route to main.py."""
        template = extract_sh_launcher_template()
        assert "--gui" in template, "Should check for --gui flag"

    def test_web_flag_is_noop(self) -> None:
        """Legacy --web flag should be ignored (no-op)."""
        template = extract_sh_launcher_template()
        assert "--web" in template, "Should mention --web for backward compat"
        web_check = re.search(r"--web\).*?;;", template, re.DOTALL)
        assert web_check, "Should have case for --web"
        assert "DESKTOP_MODE=true" not in web_check.group(), (
            "--web should not trigger desktop mode"
        )

    def test_args_filtered_correctly(self) -> None:
        """Non-mode arguments should be preserved and forwarded."""
        template = extract_sh_launcher_template()
        assert "FILTERED_ARGS" in template, "Should filter args"
        assert "main.py" in template and "FILTERED_ARGS" in template, (
            "main.py should receive filtered args"
        )


class TestPowerShellLauncher:
    """Tests for the PowerShell launcher generated by install_metis.ps1."""

    def test_default_is_web_api_and_browser(self) -> None:
        """Default path should start the API, static web server, and open browser."""
        template = extract_ps1_launcher_template()
        assert "uvicorn" in template, "Default should start the API server"
        assert "http.server" in template, "Default should start a static web server"
        assert "127.0.0.1" in template, "Launcher should bind to localhost"
        assert "8000" in template and "3000" in template, (
            "Launcher should use fixed API and web ports"
        )

    def test_desktop_mode_routes_to_main_py(self) -> None:
        """--desktop flag should route to main.py."""
        template = extract_ps1_launcher_template()
        assert "--desktop" in template, "Should check for --desktop flag"
        assert "main.py" in template, "Should run main.py for desktop mode"

    def test_gui_mode_routes_to_main_py(self) -> None:
        """--gui flag should route to main.py."""
        template = extract_ps1_launcher_template()
        assert "--gui" in template, "Should check for --gui flag"

    def test_web_flag_is_noop(self) -> None:
        """Legacy --web flag should be ignored (no-op)."""
        template = extract_ps1_launcher_template()
        desktop_check = re.search(
            r"\$desktopMode.*?=.*?\(.*?--desktop.*?\)",
            template,
            re.DOTALL,
        )
        assert desktop_check, "Should check for desktop mode"
        assert "--web" not in desktop_check.group(), (
            "--web should not be in desktop mode check"
        )

    def test_args_filtered_correctly(self) -> None:
        """Non-mode arguments should be preserved and forwarded."""
        template = extract_ps1_launcher_template()
        assert "launchArgs" in template or "$args" in template, "Should handle args"
        assert "main.py" in template, "Should run main.py"


class TestCmdLauncher:
    """Tests for the CMD launcher generated by install_metis.ps1."""

    def test_delegates_to_powershell_launcher(self) -> None:
        """CMD wrapper should delegate to the PowerShell launcher."""
        template = extract_cmd_launcher_template()
        assert "metis.ps1" in template, "CMD wrapper should reuse the PS1 launcher"
        assert "%*" in template, "Wrapper should forward all original arguments"
        assert "pwsh.exe" in template or "powershell.exe" in template, (
            "Wrapper should invoke PowerShell"
        )

    def test_args_filtered_correctly(self) -> None:
        """Non-mode arguments should be forwarded to the PowerShell launcher."""
        template = extract_cmd_launcher_template()
        assert "%*" in template, "Wrapper should forward the full argument list"


class TestInstallerSpecs:
    """Tests for installer dependency bundles."""

    def test_bash_installer_includes_api_runtime(self) -> None:
        content = INSTALL_SH.read_text(encoding="utf-8")
        assert "[runtime-all,api]" in content or "[api,runtime-all]" in content

    def test_powershell_installer_includes_api_runtime(self) -> None:
        content = INSTALL_PS1.read_text(encoding="utf-8")
        assert "[runtime-all,api]" in content or "[api,runtime-all]" in content


class TestReadmeDocs:
    """Tests for README.md launch command documentation."""

    def test_readme_documents_metis_default_as_web(self) -> None:
        """README should document `metis` as opening web UI."""
        content = README.read_text(encoding="utf-8")
        assert "metis" in content.lower()
        web_match = re.search(
            r"\|\s*\*\*Web UI\*\*\s*\|\s*`metis`\s*\|",
            content,
        )
        assert web_match, (
            "README should have Web UI as first entry with `metis` command"
        )

    def test_readme_documents_desktop_override(self) -> None:
        """README should document --desktop/--gui as Qt GUI override."""
        content = README.read_text(encoding="utf-8")
        assert "--desktop" in content, "README should document --desktop"
        assert "--gui" in content, "README should document --gui"

    def test_readme_documents_cli_mode(self) -> None:
        """README should document --cli for CLI mode."""
        content = README.read_text(encoding="utf-8")
        assert "--cli" in content, "README should document --cli"

    def test_readme_no_stale_gui_mode_reference(self) -> None:
        """README should not say 'metis' alone opens GUI (stale reference)."""
        content = README.read_text(encoding="utf-8")
        stale_patterns = [
            r'metis\s*(?:#.*?)?\s*["\']?\s*#.*?GUI mode\b',
            r'metis\s*(?:#.*?)?\s*["\']?\s*#.*?Desktop GUI\b',
        ]
        for pattern in stale_patterns:
            match = re.search(pattern, content, re.IGNORECASE)
            assert not match, (
                f"README has stale reference: {match.group() if match else ''}"
            )

    def test_readme_no_stale_web_flag_reference(self) -> None:
        """README should not present --web as preferred user mode."""
        content = README.read_text(encoding="utf-8")
        lines = content.split("\n")
        for line in lines:
            if "--web" in line and "metis" in line:
                assert "default" not in line.lower(), (
                    f"README should not present --web as default: {line.strip()}"
                )
